name: Build Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
            version: '5.15.0'
            host: 'windows'
            target: 'desktop'
            setup-python: 'false'
      - name: debug
        run: where.exe cmake
      - name: Build Windows binaries
        run: ./scripts/cmake-build-win.bat
        env:
          QTDIR: ${{ env.Qt5_Dir }}
          VSDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
          CMAKEDIR: 'C:\Program Files\CMake\bin'
          VCPKGDIR: ${{ env.PKG_CONFIG_PATH }}
